routes/web.php
<?php

Route::get('/', function () {
    return view('layouts.app');
});

Route::resource('berita', 'BeritaController');






Route::get('/o', function(){
	$test = \Faker\Factory::create();
	for ($i=0; $i < 50 ; $i++) { 
		$p = ['judul'=>$test->sentence,'konten'=>$test->paragraph];
		$new = DB::table('beritas')->insert($p);
	}
});

















// Route::get('/home', 'BiodataController@index');

// # Halaman muka, untuk menampilkan semua data pegawai yang ada. 
// # localhost:8000
// Route::get('/', [
// 	'as' => 'beranda', 
// 	'uses' => 'PegawaiController@index'
// ]);

// # Halaman yang berisi Form inputan Pegawai baru 
// # localhost:8000/buat
// Route::get('buat', [
// 	'as' => 'baru', 'uses' => 'PegawaiController@baru'
// ]);

// # Memproses Form lalu mengirimnya kedalam database 
// # localhost:8000/buat
// Route::post('buat', [
// 	'as' => 'buat', 'uses' => 'PegawaiController@buat'
// ]);

// # Menampilkan pegawai perorangan 
// # URL: localhost:8000/lihat/{id}
// Route::get('lihat/{id}', [
// 	'as' => 'lihat', 'uses' => 'PegawaiController@lihat'
// ]);

// # Form untuk mengubah isi Pegawai dalam database 
// # localhost:8000/ubah/{id}
// Route::get('ubah/{id}', [
// 	'as' => 'ubah', 'uses' => 'PegawaiController@ubah'
// ]);

// # Memproses Form lalu mengirim yang baru kedalam database 
// # localhost:8000/ubah/{id}
// Route::put('ubah/{id}', [
// 	'as' => 'ganti', 'uses' => 'PegawaiController@ganti'
// ]);

// # Tindakan untuk menghapus pegawai 
// # URL: localhost:8000/{id}/hapus
// Route::delete('hapus/{id}', [
// 	'as' => 'hapus', 'uses' => 'PegawaiController@hapus'
// ]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Berita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Berita extends Model
{
    protected $fillable = ['judul', 'konten'];
}

app/Http/Controllers/BeritaController.php
<?php

namespace App\Http\Controllers;

//jangan lupa untuk menambahkan model sebelum modelnya dipakai
use App\Berita;
use Illuminate\Http\Request;

class BeritaController extends Controller
{
    

    public function index()
    {
        // ambil semua data berita
        // $berita = Berita::all();

        // ambil semua data berita dengan paginasi tiap 20 item
        $berita = Berita::paginate(20);
        return view('berita.index', compact('berita'));
    }

    

    public function create()
    {
        return view('berita.create');
    }

   

    public function store(Request $request)
    {
        //validasi 
        $this->validate($request, ['judul'=>'required','konten'=>'required']);

        // jika name di form sama dengan nama atribut
        $berita = Berita::create($request->all());

        // jika name di form beda dengan nama atribut atau mau modifikasi data sebelum disave
        // $berita = new Berita;
        // $berita->judul = $request->judul;
        // $berita->konten = $request->konten;
        // $berita->save();
        
        //redirect ke show berita yang sudah diedit
        return redirect('berita/'.$berita->id);
    }

    

    public function show($id)
    {
        $berita = Berita::findOrFail($id);
        return view('berita.show', compact('berita'));
    }

    

    public function edit($id)
    {
        $berita = Berita::findOrFail($id);
        return view('berita.edit', compact('berita'));
    }



    public function update(Request $request, $id)
    {
        $this->validate($request, ['judul'=>'required','konten'=>'required']);
        $berita = Berita::findOrFail($id);
        $berita->update($request->all());

        //redirect ke show berita yang sudah diedit
        return redirect('berita/'.$berita->id);
    }

   

    public function destroy($id)
    {
        $berita = Berita::findOrFail($id);
        $berita->delete();
        return redirect('berita');
        
    }
}

resources/views/berita/create.blade.php
@extends('layouts.app')
@section('title','Berita')
@section('breadcrumb_1','Berita')
@section('breadcrumb_2','Tambah Berita')

@section('content')
<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		<div class="panel panel-body">
			<div class="panel-body">
				<form action="{{ route('berita.store') }}" method="POST" accept-charset="utf-8">
					@include('berita.form')
				</form>
			</div>
		</div>
	</div>
</div>
@endsection	

resources/views/berita/edit.blade.php
@extends('layouts.app')
@section('title','Berita')
@section('breadcrumb_1','Berita')
@section('breadcrumb_2','Ubah Berita')

@section('content')
<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		<div class="panel panel-body">
			<div class="panel-body">
				<form action="{{ route('berita.store') }}" method="POST" accept-charset="utf-8">
					{{ method_field('PUT') }}
					@include('berita.form')
				</form>
			</div>
		</div>
	</div>
</div>
@endsection	

resources/views/berita/form.blade.php
{{ csrf_field() }}
<input type="text" placeholder="Judul" name="judul" class="form-control" value="{{ isset($berita->judul) ? $berita->judul : null }}">
<textarea id="summernote" name="konten">{{ isset($berita->konten) ? $berita->konten : null }}</textarea>
<button type="submit" class="btn btn-success">Submit</button>
<button type="reset" class="btn btn-default">Reset</button>

resources/views/berita/index.blade.php
@extends('layouts.app')
@section('title','Berita')
@section('breadcrumb_1','Berita')
@section('breadcrumb_2','Index')

@section('content')
<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		<div class="panel panel-body">
			<div class="panel-body">
                <table id="dt" class="table table-hover table-striped dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Judul</th>
                            <th>Tanggal</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $no = 1; ?>
                        @foreach($berita as $b)
                        <tr id="{{ 'row'.$b->id }}">
                            <td>{{ $no++ }}</td>
                            <td>{{ $b->judul }}</td>
                            <td>{{ $b->created_at ? $b->created_at->format('j M Y') : null }}</td>
                            <td>
                                <form action="{{ url('/berita', ['id' => $b->id]) }}" method="post" id="delete-form">
                                    <div class="btn-group  btn-group-sm">
                                        <a class="btn btn-info" href="{{ url('berita/'.$b->id) }}" title="">Detail</a>
                                        <a href="{{ url('berita/'.$b->id.'/edit') }}" class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Ubah">Edit</a>
                                            {!! method_field('delete') !!}
                                            {!! csrf_field() !!}
                                            <button class="btn btn-danger" onclick="return confirm('Delete this data?')">Delete</button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>  
                </table>
                //mencetak paginator
                {{ $berita->links() }}
            </div>
        </div>
    </div>
</div>
@endsection	

resources/views/berita/show.blade.php
@extends('layouts.app')
@section('title','Berita')
@section('breadcrumb_1','Berita')
@section('breadcrumb_2','Detail')

@section('content')
<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		<div class="panel blog blog-details">
			<div class="panel-body">
				<div class="blog-title media-block">
					<div class="media-right textright">
						<a href="#" class="btn btn-icon demo-psi-twitter icon-lg add-tooltip" data-original-title="Twitter" data-container="body"></a>
						<a href="#" class="btn btn-icon demo-psi-instagram icon-lg add-tooltip" data-original-title="Instagram" data-container="body"></a>
					</div>
					<div class="media-body">
						<a href="#" class="btn-link">
							<h1>{{ $berita->judul }}</h1>
						</a>
						{{-- <p>By <a href="#" class="btn-link">Aaron Chavez</a></p> --}}
					</div>
				</div>
				<div class="blog-content">
					
					<div class="blog-body">
						{{ $berita->konten }}
					</div>
				</div>
				<div class="blog-footer">
					<div class="media-left">
						<span class="label label-success">{{ $berita->created_at->diffForHumans() }}</span>
						<small>Posted by : <a href="#" class="btn-link">?</a></small>
					</div>
					<div class="media-body text-right">
						<span class="mar-rgt"><i class="demo-pli-heart-2 icon-fw"></i>519</span>
						<i class="demo-pli-speech-bubble-5 icon-fw"></i>23
					</div>
				</div>

			</div>
		</div>
	</div>
</div>
@endsection	